name: Pelorus Github Release

on:
  push:
    tags:
      - '*'

jobs:
  github-release:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout pelorus
        uses: actions/checkout@v2

      - name: Create Changelog
        id: create_changelog
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          configuration: ".github/github-changelog-builder-conf.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{steps.create_changelog.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
