name: Pelorus Release Drafter

on:
  push:
    branches:
      - master
      - main

  # pull_request required to auto label PRs
  pull_request:
    types: [opened, reopened, synchronize]
    
jobs:
  release_drafter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pelorus
        uses: actions/checkout@v2

      - uses: release-drafter/release-drafter@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}